{
  "ras-api": {
    "2": {
      "0": {
        "components": {
          "securitySchemes": {
            "User-Restricted": {
              "description": "HMRC supports OAuth 2.0 for authenticating [user-restricted](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) API requests using an OAuth 2.0 Bearer Token in the Authorization header.",
              "flows": {
                "authorizationCode": {
                  "authorizationUrl": "https://api.service.hmrc.gov.uk/oauth/authorize",
                  "refreshUrl": "https://api.service.hmrc.gov.uk/oauth/refresh",
                  "scopes": {
                    "read:ras": "Access to Relief At Source API's"
                  },
                  "tokenUrl": "https://api.service.hmrc.gov.uk/oauth/token"
                }
              },
              "type": "oauth2"
            }
          }
        },
        "info": {
          "title": "Residency status for relief at source",
          "version": "2.0"
        },
        "openapi": "3.0.3",
        "paths": {
          "/individuals/relief-at-source/residency-status": {
            "post": {
              "deprecated": false,
              "description": "Pension Scheme Administrators can find out if a pension scheme member pays tax in Scotland, Wales or in the rest of the UK. They can apply the correct rate of Income Tax to their relief at source contributions.\nFrom 1 January to 5 April, the API will return currentYearResidencyStatus and nextYearForecastResidencyStatus.\nFrom 6 April to 31 December, the API will only return currentYearResidencyStatus.\n",
              "operationId": "checkIndividualResidency",
              "parameters": [
                {
                  "description": "Specifies the response format and the [version](/api-documentation/docs/reference-guide#versioning) of the API to be used.",
                  "in": "header",
                  "name": "Accept",
                  "required": true,
                  "schema": {
                    "type": "string",
                    "enum": [
                      "application/vnd.hmrc.2.0+json"
                    ]
                  },
                  "style": "simple"
                },
                {
                  "description": "Specifies the format of the request body, which must be JSON.",
                  "in": "header",
                  "name": "Content-Type",
                  "required": true,
                  "schema": {
                    "type": "string",
                    "enum": [
                      "application/json"
                    ]
                  },
                  "style": "simple"
                },
                {
                  "description": "An [OAuth 2.0 Bearer Token](/api-documentation/docs/authorisation/user-restricted-endpoints) with the `read:ras` scope.",
                  "in": "header",
                  "name": "Authorization",
                  "required": true,
                  "schema": {
                    "type": "string",
                    "example": "Bearer bb7fed3fe10dd235a2ccda3d50fb"
                  },
                  "style": "simple"
                }
              ],
              "requestBody": {
                "content": {
                  "application/json": {
                    "examples": {
                      "scotland-curr-year-scotland-next-year": {
                        "description": "Individual with current and next year as Scotland resident.",
                        "value": {
                          "dateOfBirth": "1982-02-17",
                          "firstName": "Joe",
                          "lastName": "Bloggs",
                          "nino": "CC123456C"
                        }
                      },
                      "scotland-curr-year-uk-next-year": {
                        "description": "Individual with current year as Scotland and next year as rest of the UK resident.",
                        "value": {
                          "dateOfBirth": "1969-06-09",
                          "firstName": "Jane",
                          "lastName": "Doe",
                          "nino": "LR325154B"
                        }
                      },
                      "uk-curr-year-scotland-next-year": {
                        "description": "Individual with current year as rest of the UK and next year as Scotland resident.",
                        "value": {
                          "dateOfBirth": "1975-05-25",
                          "firstName": "John",
                          "lastName": "Smith",
                          "nino": "BB123456B"
                        }
                      },
                      "uk-curr-year-wales-next-year": {
                        "description": "Individual with current year as rest of the UK and next year as Wales resident.",
                        "value": {
                          "dateOfBirth": "1950-10-20",
                          "firstName": "John",
                          "lastName": "Johny",
                          "nino": "SG325450C"
                        }
                      },
                      "unregistered-nino-1": {
                        "description": "Member with an unregistered nino number",
                        "value": {
                          "dateOfBirth": "1965-01-01",
                          "firstName": "Austin",
                          "lastName": "Powers",
                          "nino": "CC432567B"
                        }
                      },
                      "unregistered-nino-2": {
                        "description": "Member with an unregistered nino number",
                        "value": {
                          "dateOfBirth": "1965-02-01",
                          "firstName": "Jake",
                          "lastName": "John",
                          "nino": "CB432564B"
                        }
                      },
                      "wales-curr-year-wales-next-year": {
                        "description": "Individual with current and next year as Wales resident.",
                        "value": {
                          "dateOfBirth": "1962-07-07",
                          "firstName": "Jack",
                          "lastName": "Oscar",
                          "nino": "AA246255A"
                        }
                      }
                    },
                    "schema": {
                      "allOf": [
                        {
                          "title": "Residency status request",
                          "required": [
                            "nino",
                            "firstName",
                            "lastName",
                            "dateOfBirth"
                          ],
                          "type": "object",
                          "properties": {
                            "nino": {
                              "pattern": "^((?!(BG|GB|KN|NK|NT|TN|ZZ)|(D|F|I|Q|U|V)[A-Z]|[A-Z](D|F|I|O|Q|U|V))[A-Z]{2})[0-9]{6}[A-D]?$",
                              "type": "string",
                              "description": "The pension scheme member\u2019s National Insurance number.",
                              "example": "BB123456B"
                            },
                            "firstName": {
                              "pattern": "^[a-zA-Z &`\\-\\'^]{1,35}$",
                              "type": "string",
                              "description": "The pension scheme member\u2019s first name.",
                              "example": "John"
                            },
                            "lastName": {
                              "pattern": "^[a-zA-Z &`\\-\\'^]{1,35}$",
                              "type": "string",
                              "description": "The pension scheme member\u2019s last name.",
                              "example": "Smith"
                            },
                            "dateOfBirth": {
                              "type": "string",
                              "description": "The pension scheme member\u2019s date of birth. This cannot be in the future.",
                              "example": "1975-05-25",
                              "format": "date",
                              "pattern": "^\\d{4}-\\d{2}-\\d{2}$"
                            }
                          }
                        }
                      ]
                    }
                  }
                },
                "required": true
              },
              "responses": {
                "200": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "scotland-curr-year-scotland-next-year": {
                          "description": "Individual with current and next year as Scotland resident.",
                          "value": {
                            "currentYearResidencyStatus": "scotResident",
                            "nextYearForecastResidencyStatus": "scotResident"
                          }
                        },
                        "scotland-curr-year-uk-next-year": {
                          "description": "Individual with current year as Scotland and next year as rest of the UK resident.",
                          "value": {
                            "currentYearResidencyStatus": "scotResident",
                            "nextYearForecastResidencyStatus": "otherUKResident"
                          }
                        },
                        "uk-curr-year-scotland-next-year": {
                          "description": "Individual with current year as rest of the UK and next year as Scotland resident.",
                          "value": {
                            "currentYearResidencyStatus": "otherUKResident",
                            "nextYearForecastResidencyStatus": "scotResident"
                          }
                        },
                        "uk-curr-year-wales-next-year": {
                          "description": "Individual with current year as rest of the UK and next year as Wales resident.",
                          "value": {
                            "currentYearResidencyStatus": "otherUKResident",
                            "nextYearForecastResidencyStatus": "welshResident"
                          }
                        },
                        "wales-curr-year-wales-next-year": {
                          "description": "Individual with current and next year as Wales resident.",
                          "value": {
                            "currentYearResidencyStatus": "welshResident",
                            "nextYearForecastResidencyStatus": "welshResident"
                          }
                        }
                      },
                      "schema": {
                        "allOf": [
                          {
                            "title": "Relief at source residency status response",
                            "required": [
                              "currentYearResidencyStatus"
                            ],
                            "type": "object",
                            "properties": {
                              "currentYearResidencyStatus": {
                                "title": "UK residency status type",
                                "enum": [
                                  "scotResident",
                                  "welshResident",
                                  "otherUKResident"
                                ],
                                "type": "string"
                              },
                              "nextYearForecastResidencyStatus": {
                                "title": "UK residency status type",
                                "enum": [
                                  "scotResident",
                                  "welshResident",
                                  "otherUKResident"
                                ],
                                "type": "string"
                              }
                            }
                          }
                        ]
                      }
                    }
                  },
                  "description": "OK"
                },
                "400": {
                  "content": {
                    "application/json": {
                      "example": {
                        "code": "BAD_REQUEST",
                        "message": "Bad Request"
                      },
                      "schema": {
                        "allOf": [
                          {
                            "title": "Error response",
                            "required": [
                              "code",
                              "message"
                            ],
                            "type": "object",
                            "properties": {
                              "code": {
                                "title": "Error code type",
                                "enum": [
                                  "BAD_REQUEST"
                                ],
                                "type": "string"
                              },
                              "message": {
                                "type": "string"
                              }
                            }
                          }
                        ]
                      }
                    }
                  },
                  "description": "Bad Request"
                },
                "403": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "unregistered-nino-1": {
                          "description": "Member with an unregistered nino number",
                          "value": {
                            "code": "STATUS_UNAVAILABLE",
                            "message": "Cannot provide a residency status for this pension scheme member."
                          }
                        },
                        "unregistered-nino-2": {
                          "description": "Member with an unregistered nino number",
                          "value": {
                            "code": "STATUS_UNAVAILABLE",
                            "message": "Cannot provide a residency status for this pension scheme member."
                          }
                        }
                      },
                      "schema": {
                        "allOf": [
                          {
                            "title": "Error response",
                            "required": [
                              "code",
                              "message"
                            ],
                            "type": "object",
                            "properties": {
                              "code": {
                                "title": "Error code type",
                                "enum": [
                                  "STATUS_UNAVAILABLE"
                                ],
                                "type": "string"
                              },
                              "message": {
                                "type": "string"
                              }
                            }
                          }
                        ]
                      }
                    }
                  },
                  "description": "Forbidden"
                },
                "401": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "MISSING_CREDENTIALS",
                              "INVALID_CREDENTIALS",
                              "UNAUTHORIZED",
                              "INCORRECT_ACCESS_TOKEN_TYPE"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "MISSING_CREDENTIALS",
                          "message": "Authentication information is not provided"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "404": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "MATCHING_RESOURCE_NOT_FOUND"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "MATCHING_RESOURCE_NOT_FOUND",
                          "message": "No endpoint for the request path"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "405": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "METHOD_NOT_ALLOWED"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "METHOD_NOT_ALLOWED",
                          "message": "Request method must be one of GET, PUT, POST, PATCH, DELETE or OPTIONS"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "406": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "ACCEPT_HEADER_INVALID"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "ACCEPT_HEADER_INVALID",
                          "message": "Missint or invalid Accept header"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "429": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "MESSAGE_THROTTLED_OUT"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "MESSAGE_THROTTLED_OUT",
                          "message": "The application has reached its maximum rate limit"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "500": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "oneOf": [
                          {
                            "properties": {
                              "code": {
                                "type": "string",
                                "description": "Error Code",
                                "enum": [
                                  "INTERNAL_SERVER_ERROR"
                                ]
                              },
                              "message": {
                                "type": "string"
                              }
                            },
                            "type": "object",
                            "example": {
                              "code": "INTERNAL_SERVER_ERROR",
                              "message": "Internal server error"
                            }
                          },
                          {
                            "type": "string",
                            "example": "Failed to process request"
                          }
                        ]
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "501": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "NOT_IMPLEMENTED"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "NOT_IMPLEMENTED",
                          "message": "API not implemented or deployed"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "503": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "SERVER_ERROR",
                              "SCHEDULED_MAINTENANCE"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "SCHEDULED_MAINTENANCE",
                          "message": "Scheduled maintenance"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "504": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "GATEWAY_TIMEOUT"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "GATEWAY_TIMEOUT",
                          "message": "Request timed out"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                }
              },
              "security": [
                {
                  "User-Restricted": [
                    "read:ras"
                  ]
                }
              ],
              "summary": "Check if an individual is a Scotland, Wales or rest of the UK resident"
            }
          }
        },
        "servers": [
          {
            "description": "Sandbox",
            "url": "https://test-api.service.hmrc.gov.uk"
          },
          {
            "description": "Production",
            "url": "https://api.service.hmrc.gov.uk"
          }
        ]
      }
    }
  }
}