{
  "self-assessment-liability-api": {
    "1": {
      "0": {
        "components": {
          "securitySchemes": {
            "User-Restricted": {
              "description": "HMRC supports OAuth 2.0 for authenticating user restricted API requests using an OAuth 2.0 Bearer Token in the AUTHORIZATION header. Please see the [developer hub](https://developer.service.hmrc.gov.uk/api-documentation/docs/authorisation/user-restricted-endpoints) for more details.",
              "flows": {
                "authorizationCode": {
                  "authorizationUrl": "https://api.service.hmrc.gov.uk/oauth/authorize",
                  "refreshUrl": "https://api.service.hmrc.gov.uk/oauth/refresh",
                  "scopes": {
                    "read:self-assessment": "Read self-assessment data"
                  },
                  "tokenUrl": "https://api.service.hmrc.gov.uk/oauth/token"
                }
              },
              "type": "oauth2"
            }
          }
        },
        "info": {
          "title": "View Self Assessment Account",
          "version": "0.3.0"
        },
        "openapi": "3.0.3",
        "paths": {
          "/individuals/self-assessment/breakdown/{utr}": {
            "get": {
              "description": "<b>Examples</b><br>\n/individuals/self-assessment/breakdown/1234567890?fromDate=2024-08-04\n",
              "parameters": [
                {
                  "description": "An OAuth 2.0 Bearer Token with the *read:self-assessment* scope.\n",
                  "in": "header",
                  "name": "Authorization",
                  "required": true,
                  "schema": {
                    "type": "string",
                    "example": "Bearer bb7fed3fe10dd235a2ccda3d50fb"
                  }
                },
                {
                  "description": "\"The start date for the tax data retrieval period (YYYY-MM-DD format)\"\n",
                  "example": "2023-01-01",
                  "in": "query",
                  "name": "fromDate",
                  "required": false,
                  "schema": {
                    "type": "string",
                    "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                  }
                },
                {
                  "description": "Unique Tax Payer Reference",
                  "in": "path",
                  "name": "utr",
                  "required": true,
                  "schema": {
                    "type": "string",
                    "pattern": "^\\d{10}$",
                    "example": "1234567890"
                  }
                }
              ],
              "responses": {
                "200": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "example 1": {
                          "value": {
                            "balanceDetails": {
                              "codedOutDetail": [
                                {
                                  "effectiveEndDate": "2024-04-01",
                                  "effectiveStartDate": "2023-04-06",
                                  "totalAmount": 200
                                }
                              ],
                              "earliestPayableDueDate": "2025-04-30",
                              "earliestPendingDueDate": "2025-07-15",
                              "totalBalance": 2000,
                              "totalCreditAvailable": 0,
                              "totalOverdueBalance": 500,
                              "totalPayableBalance": 500,
                              "totalPendingBalance": 1500
                            },
                            "chargeDetails": [
                              {
                                "amendments": [
                                  {
                                    "amendmentAmount": 500,
                                    "amendmentDate": "2025-04-15",
                                    "amendmentReason": "Payment",
                                    "isPaymentRelated": true,
                                    "paymentDate": "2025-04-10",
                                    "paymentMethod": "bank_transfer"
                                  }
                                ],
                                "chargeAmount": 1250,
                                "chargeId": "AB1234567",
                                "chargeType": "ITSA",
                                "creationDate": "2025-01-15",
                                "dueDate": "2025-04-30",
                                "outstandingAmount": 500,
                                "taxYear": "2024-2025"
                              },
                              {
                                "accruingInterestPeriod": {
                                  "interestEndDate": "2024-12-01",
                                  "interestStartDate": "2024-05-01"
                                },
                                "accruingInterestRate": 0.05,
                                "amendments": [
                                  {
                                    "amendmentAmount": 2058.33,
                                    "amendmentDate": "2024-12-08",
                                    "amendmentReason": "Payment",
                                    "isPaymentRelated": true,
                                    "paymentDate": "2024-12-03",
                                    "paymentMethod": "bank_transfer"
                                  }
                                ],
                                "chargeAmount": 2200,
                                "chargeId": "EF2345678",
                                "chargeType": "NICS",
                                "creationDate": "2024-02-10",
                                "dueDate": "2024-04-01",
                                "outstandingAmount": 0,
                                "outstandingInterestDue": 20,
                                "taxYear": "2023-2024"
                              },
                              {
                                "chargeAmount": 1500,
                                "chargeId": "KL3456789",
                                "chargeType": "VATC",
                                "creationDate": "2025-05-22",
                                "dueDate": "2025-07-15",
                                "outstandingAmount": 1500,
                                "taxYear": "2025-2026"
                              }
                            ],
                            "paymentHistoryDetails": [
                              {
                                "allocationReference": "AB1234567",
                                "paymentAmount": 500,
                                "paymentDate": "2025-04-11",
                                "paymentMethod": "bank_transfer",
                                "paymentReference": "PAY123456",
                                "processedDate": "2025-04-15"
                              },
                              {
                                "allocationReference": "EF2345678",
                                "paymentAmount": 2058.33,
                                "paymentDate": "2024-12-04",
                                "paymentMethod": "bank_transfer",
                                "paymentReference": "PAY112233",
                                "processedDate": "2024-12-08"
                              },
                              {
                                "allocationReference": "EF2345678",
                                "paymentAmount": 200,
                                "paymentDate": "2023-12-04",
                                "paymentMethod": "bank_transfer",
                                "paymentReference": "PAY888233",
                                "processedDate": "2023-12-08"
                              }
                            ],
                            "refundDetails": [
                              {
                                "interestAddedToRefund": 5.25,
                                "refundDate": "2024-01-10",
                                "refundDescription": "From overpayment from return 05 APR 23",
                                "refundMethod": "bank transfer",
                                "refundRequestAmount": 350,
                                "refundRequestDate": "2023-12-12",
                                "refundStatus": "processed",
                                "totalRefundAmount": 355.25
                              }
                            ]
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "required": [
                          "balanceDetails"
                        ],
                        "description": "Provides a summary of the taxpayer's current position",
                        "properties": {
                          "balanceDetails": {
                            "allOf": [
                              {
                                "type": "object",
                                "properties": {
                                  "totalOverdueBalance": {
                                    "description": "Total of all charges with a due date in the past.",
                                    "allOf": [
                                      {
                                        "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 99999999999.99,
                                        "multipleOf": 0.01
                                      }
                                    ]
                                  },
                                  "totalPayableBalance": {
                                    "description": "Total of all charges due within the next 30 days.",
                                    "allOf": [
                                      {
                                        "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 99999999999.99,
                                        "multipleOf": 0.01
                                      }
                                    ]
                                  },
                                  "earliestPayableDueDate": {
                                    "description": "The earliest due date for charges due within the next 30 days.",
                                    "allOf": [
                                      {
                                        "type": "string",
                                        "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                      }
                                    ]
                                  },
                                  "totalPendingBalance": {
                                    "description": "Total of all charges due in 30 days or more.",
                                    "allOf": [
                                      {
                                        "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 99999999999.99,
                                        "multipleOf": 0.01
                                      }
                                    ]
                                  },
                                  "earliestPendingDueDate": {
                                    "description": "The earliest due date for charges due in 30 days or more.",
                                    "allOf": [
                                      {
                                        "type": "string",
                                        "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                      }
                                    ]
                                  },
                                  "totalBalance": {
                                    "description": "Combined total of overdue, payable, and pending charges.",
                                    "allOf": [
                                      {
                                        "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 99999999999.99,
                                        "multipleOf": 0.01
                                      }
                                    ]
                                  },
                                  "totalCreditAvailable": {
                                    "description": "Total credit currently accrued on the account.",
                                    "allOf": [
                                      {
                                        "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                        "type": "number",
                                        "minimum": 0,
                                        "maximum": 99999999999.99,
                                        "multipleOf": 0.01
                                      }
                                    ]
                                  },
                                  "codedOutDetail": {
                                    "description": "Coded out liabilities",
                                    "allOf": [
                                      {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "properties": {
                                            "totalAmount": {
                                              "description": "Total past/future amount adjustments via taxcode changes.",
                                              "allOf": [
                                                {
                                                  "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                                  "type": "number",
                                                  "minimum": 0,
                                                  "maximum": 99999999999.99,
                                                  "multipleOf": 0.01
                                                }
                                              ]
                                            },
                                            "effectiveStartDate": {
                                              "description": "Effective start date of coding",
                                              "allOf": [
                                                {
                                                  "type": "string",
                                                  "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                }
                                              ]
                                            },
                                            "effectiveEndDate": {
                                              "description": "Effective end date of coding",
                                              "allOf": [
                                                {
                                                  "type": "string",
                                                  "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                }
                                              ]
                                            }
                                          },
                                          "additionalProperties": false,
                                          "required": [
                                            "totalAmount",
                                            "effectiveStartDate",
                                            "effectiveEndDate"
                                          ]
                                        }
                                      }
                                    ]
                                  }
                                },
                                "required": [
                                  "totalOverdueBalance",
                                  "totalPayableBalance",
                                  "totalPendingBalance",
                                  "totalBalance",
                                  "totalCreditAvailable"
                                ]
                              }
                            ]
                          },
                          "chargeDetails": {
                            "allOf": [
                              {
                                "type": "array",
                                "items": {
                                  "description": "Provides a summary of historic charges and amendments made to a charge",
                                  "allOf": [
                                    {
                                      "required": [
                                        "chargeAmount",
                                        "chargeId",
                                        "chargeType",
                                        "creationDate",
                                        "dueDate",
                                        "outstandingAmount",
                                        "taxYear"
                                      ],
                                      "type": "object",
                                      "properties": {
                                        "accruingInterest": {
                                          "description": "Interest currently accruing on the charge.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "accruingInterestPeriod": {
                                          "description": "The date range over which interest applies to this charge.",
                                          "allOf": [
                                            {
                                              "type": "object",
                                              "properties": {
                                                "interestStartDate": {
                                                  "allOf": [
                                                    {
                                                      "type": "string",
                                                      "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                    }
                                                  ]
                                                },
                                                "interestEndDate": {
                                                  "allOf": [
                                                    {
                                                      "type": "string",
                                                      "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                    }
                                                  ]
                                                }
                                              }
                                            }
                                          ]
                                        },
                                        "accruingInterestRate": {
                                          "description": "The current interest rate being applied.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "amendments": {
                                          "allOf": [
                                            {
                                              "type": "array",
                                              "items": {
                                                "description": "Provides information about any adjustments made to a charge due to payments, credits or appeals.",
                                                "allOf": [
                                                  {
                                                    "required": [
                                                      "amendmentAmount",
                                                      "amendmentDate",
                                                      "amendmentReason",
                                                      "isPaymentRelated"
                                                    ],
                                                    "type": "object",
                                                    "properties": {
                                                      "amendmentDate": {
                                                        "description": "Date the amendment was made.",
                                                        "allOf": [
                                                          {
                                                            "type": "string",
                                                            "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                          }
                                                        ]
                                                      },
                                                      "amendmentAmount": {
                                                        "description": "Amount added or reduced from the outstanding charge amount.",
                                                        "allOf": [
                                                          {
                                                            "description": "Currency amount. 13-digits total with 2 decimal places",
                                                            "type": "number",
                                                            "minimum": -99999999999.99,
                                                            "maximum": 99999999999.99,
                                                            "multipleOf": 0.01
                                                          }
                                                        ]
                                                      },
                                                      "amendmentReason": {
                                                        "description": "Reason the change was applied.",
                                                        "allOf": [
                                                          {
                                                            "type": "string",
                                                            "minLength": 1,
                                                            "maxLength": 100
                                                          }
                                                        ]
                                                      },
                                                      "isPaymentRelated": {
                                                        "allOf": [
                                                          {
                                                            "type": "boolean"
                                                          }
                                                        ]
                                                      },
                                                      "paymentMethod": {
                                                        "description": "How the payment was made (e.g. bank transfer).",
                                                        "allOf": [
                                                          {
                                                            "type": "string",
                                                            "minLength": 1,
                                                            "maxLength": 30
                                                          }
                                                        ]
                                                      },
                                                      "paymentDate": {
                                                        "description": "Date the payment was made.",
                                                        "allOf": [
                                                          {
                                                            "type": "string",
                                                            "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                                          }
                                                        ]
                                                      }
                                                    },
                                                    "additionalProperties": false
                                                  }
                                                ]
                                              }
                                            }
                                          ]
                                        },
                                        "chargeId": {
                                          "description": "The unique identifier for the charge.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^[A-Za-z0-9-]{1,18}$"
                                            }
                                          ]
                                        },
                                        "chargeType": {
                                          "description": "Type of charge (e.g. ITSA, NICS, POA).",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "minLength": 1,
                                              "maxLength": 30
                                            }
                                          ]
                                        },
                                        "chargeAmount": {
                                          "description": "The original amount of the charge.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "creationDate": {
                                          "description": "Date the charge was created.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        },
                                        "dueDate": {
                                          "description": "Date the charge must be paid by.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        },
                                        "outstandingInterestDue": {
                                          "description": "Amount of interest unpaid from the total accrued interest.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "outstandingAmount": {
                                          "description": "Remaining balance on the charge still to be paid.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "taxYear": {
                                          "description": "The tax year the charge relates to.",
                                          "allOf": [
                                            {
                                              "allOf": [
                                                {
                                                  "type": "string",
                                                  "pattern": "^([0-9]{4})-([0-9]{4})$"
                                                }
                                              ]
                                            }
                                          ]
                                        }
                                      },
                                      "additionalProperties": false
                                    }
                                  ]
                                }
                              }
                            ]
                          },
                          "refundDetails": {
                            "allOf": [
                              {
                                "type": "array",
                                "items": {
                                  "description": "Information about refunds",
                                  "allOf": [
                                    {
                                      "type": "object",
                                      "required": [
                                        "totalRefundAmount",
                                        "refundRequestAmount"
                                      ],
                                      "properties": {
                                        "refundDate": {
                                          "description": "The date that the refund was issued.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        },
                                        "interestAddedToRefund": {
                                          "description": "Any interest added to the refund at the point of processing.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "totalRefundAmount": {
                                          "description": "The total amount refunded, including any added interest.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "refundMethod": {
                                          "description": "The method that was used to make the refund (BACS etc).",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^[a-zA-Z ]{1,30}$"
                                            }
                                          ]
                                        },
                                        "refundDescription": {
                                          "description": "Additional information about the refund.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^[a-zA-Z0-9 ]{1,100}$"
                                            }
                                          ]
                                        },
                                        "refundRequestAmount": {
                                          "description": "The amount requested for refund.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "refundRequestDate": {
                                          "description": "The date that the refund was requested.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        },
                                        "refundStatus": {
                                          "description": "The current progress of the refund.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^[a-zA-Z ]{1,32}$"
                                            }
                                          ]
                                        }
                                      },
                                      "additionalProperties": false
                                    }
                                  ]
                                }
                              }
                            ]
                          },
                          "paymentHistoryDetails": {
                            "allOf": [
                              {
                                "type": "array",
                                "items": {
                                  "description": "History of previous payments",
                                  "allOf": [
                                    {
                                      "type": "object",
                                      "required": [
                                        "paymentAmount",
                                        "paymentDate"
                                      ],
                                      "properties": {
                                        "allocationReference": {
                                          "description": "Reference of the charge this payment has been allocated to.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "minLength": 1,
                                              "maxLength": 200
                                            }
                                          ]
                                        },
                                        "processedDate": {
                                          "description": "The date the payment was processed by HMRC.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        },
                                        "paymentAmount": {
                                          "description": "The amount that was paid.",
                                          "allOf": [
                                            {
                                              "description": "All numeric fields. 13-digits total with 2 decimal places and positive",
                                              "type": "number",
                                              "minimum": 0,
                                              "maximum": 99999999999.99,
                                              "multipleOf": 0.01
                                            }
                                          ]
                                        },
                                        "paymentMethod": {
                                          "description": "How the payment was made (e.g. bank transfer, card).",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "minLength": 1,
                                              "maxLength": 30
                                            }
                                          ]
                                        },
                                        "paymentReference": {
                                          "description": "The reference used for the payment.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "minLength": 1,
                                              "maxLength": 30
                                            }
                                          ]
                                        },
                                        "paymentDate": {
                                          "description": "The date payment was made.",
                                          "allOf": [
                                            {
                                              "type": "string",
                                              "pattern": "^(((19|20)([2468][048]|[13579][26]|0[48])|2000)[-]02[-]29|((19|20)[0-9]{2}[-](0[469]|11)[-](0[1-9]|1[0-9]|2[0-9]|30)|(19|20)[0-9]{2}[-](0[13578]|1[02])[-](0[1-9]|[12][0-9]|3[01])|(19|20)[0-9]{2}[-]02[-](0[1-9]|1[0-9]|2[0-8])))$"
                                            }
                                          ]
                                        }
                                      },
                                      "additionalProperties": false
                                    }
                                  ]
                                }
                              }
                            ]
                          }
                        },
                        "additionalProperties": false
                      }
                    }
                  },
                  "description": "Successful"
                },
                "400": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error400ResponseBodyExample": {
                          "value": {
                            "message": "Invalid request format or parameters."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Bad request"
                },
                "401": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error401ResponseBodyExample": {
                          "value": {
                            "message": "Authorisation failed."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Unauthorised"
                },
                "403": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error403ResponseBodyExample": {
                          "value": {
                            "message": "Access not permitted."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Forbidden"
                },
                "404": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error404ResponseBodyExample": {
                          "value": {
                            "message": "No data found for the UTR provided."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Not found"
                },
                "500": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error500ResponseBodyExample": {
                          "value": {
                            "message": "Unexpected internal error. Please contact service desk."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Internal Server Error"
                },
                "503": {
                  "content": {
                    "application/json": {
                      "examples": {
                        "error503ResponseBodyExample": {
                          "value": {
                            "message": "Service unavailable. Please try again later."
                          }
                        }
                      },
                      "schema": {
                        "type": "object",
                        "properties": {
                          "message": {
                            "allOf": [
                              {
                                "type": "string",
                                "description": "Error message."
                              }
                            ]
                          }
                        },
                        "additionalProperties": true,
                        "required": [
                          "message"
                        ]
                      }
                    }
                  },
                  "description": "Service unavailable"
                },
                "405": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "METHOD_NOT_ALLOWED"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "METHOD_NOT_ALLOWED",
                          "message": "Request method must be one of GET, PUT, POST, PATCH, DELETE or OPTIONS"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "406": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "ACCEPT_HEADER_INVALID"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "ACCEPT_HEADER_INVALID",
                          "message": "Missint or invalid Accept header"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "429": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "MESSAGE_THROTTLED_OUT"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "MESSAGE_THROTTLED_OUT",
                          "message": "The application has reached its maximum rate limit"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "501": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "NOT_IMPLEMENTED"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "NOT_IMPLEMENTED",
                          "message": "API not implemented or deployed"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                },
                "504": {
                  "content": {
                    "application/json": {
                      "schema": {
                        "properties": {
                          "code": {
                            "type": "string",
                            "description": "Error Code",
                            "enum": [
                              "GATEWAY_TIMEOUT"
                            ]
                          },
                          "message": {
                            "type": "string"
                          }
                        },
                        "type": "object",
                        "example": {
                          "code": "GATEWAY_TIMEOUT",
                          "message": "Request timed out"
                        }
                      }
                    }
                  },
                  "description": "UNAUTHORISED Response"
                }
              },
              "security": [
                {
                  "User-Restricted": [
                    "read:self-assessment"
                  ]
                }
              ],
              "summary": "Account Details",
              "tags": [
                "Self Assessment Account Details"
              ]
            }
          }
        },
        "servers": [
          {
            "description": "Sandbox",
            "url": "https://test-api.service.hmrc.gov.uk"
          },
          {
            "description": "Production",
            "url": "https://api.service.hmrc.gov.uk"
          }
        ],
        "tags": []
      }
    }
  }
}